### ISSUE TITLE
Error message of concern?

### ISSUE THREAD

**Issue by sashakames** [esgf-nimbus/getting_started#19] opened 2021-03-23 21:45 UTC
Got this one:

Server Not Running
Your server at /jupyterhub/user/sashakames/ is not running. Would you like to restart it?

I "Dismissed" and so far no issue.

**Comment by jasonb5** [comment] 2021-03-23 21:51
@sashakames 
I updated the images and some configuration today. This might be a left over from invalid jupyterlab api tokens, since the jupyterhub service got updated. If you don't see it again we should be able to close this, if i can reproduce this i'll add and entry into the FAQ.

**Comment by sashakames** [comment] 2021-03-25 17:46
Saw it again, but seems like a false positive of sorts,  my instance was fine overnight with the laptop left opened an plugged in.

**Comment by jasonb5** [comment] 2021-03-25 19:28
Hmm I wonder what time it was, i had pushed a change later last night, this might have caused it.

**Comment by jasonb5** [comment] 2021-03-30 20:14
I think we can chaulk this up to me updating the JupyterHub so let's close this issue. If the error comes up and you can't access the environment open a new bug for that.

**Closed as completed by jasonb5** 2021-03-30 20:14 UTC
